# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 105c5f2fabc72be54951c1901acf90a2ce9f5d94cca858de178a9dcce80907b9eea3f3ca9fe7558c0121772a8096fef2f6503d8aaa232136aaf65acdc2cd4bd3

test:
  secret_key_base: aafb5b7506f71035c214d22c86713fa6870e59edd7c07b5062f8d8d4901b36bc6e84f32eace47308f441135632d19d96c2896fcc3c9fdb4a7318e919b751a976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
